- id: doi:10.1177/14614448231212822
  type: paper
  image: images/publications.jpg

- id: doi:10.1080/10447318.2023.2256554
  type: paper
  image: images/publications.jpg

- id: doi:10.1071/SH22025
  type: paper
  image: images/publications.jpg

- id: doi:10.1093/her/cyad012
  type: paper
  image: images/publications.jpg

- id: doi:10.1080/10447318.2022.2163350
  type: paper
  image: images/publications.jpg

- id: doi:10.1080/17543266.2022.2125589
  type: paper
  image: images/publications.jpg


# manually provide all citation details
- id: doi:10.15997/j.cnki.qnjz.2023.02.019
  title: 人机传播的内涵、外延及研究议程
  authors:
    - 牟怡
  publisher: 青年记者
  date: 2023-02-01
  link: 
  type: paper
  image: images/publications.jpg


