- id: doi:10.1177/14614448231212822
  type: paper
  image: images/publications.jpg

- id: doi:10.1080/10447318.2023.2256554
  type: paper
  image: images/publications.jpg

- id: doi:10.1071/SH22025
  type: paper
  image: images/publications.jpg

- id: doi:10.1093/her/cyad012
  type: paper
  image: images/publications.jpg

- id: doi:10.1080/10447318.2022.2163350
  type: paper
  image: images/publications.jpg

- id: doi:10.1080/17543266.2022.2125589
  type: paper
  image: images/publications.jpg
  
- title: 人机传播的内涵、外延及研究议程
  type: paper
  image: images/publications.jpg
  authors:
    - 牟怡
  publisher: 青年记者
  date: '2023-01-25'
  link: http://www.qnjz.com/index.php?m=content&c=index&a=show&catid=7&id=37776

- title: 老年残障群体新媒体复合赋权的条件与路径考察
  type: paper
  image: images/publications.jpg
  authors:
    - 张林
    - 牟怡
  publisher: 新闻大学
  date: '2023-05-15'
  link: https://chn.oversea.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2023&filename=XWDX202305008&uniplatform=OVERSEA&v=8rOqUyEtECbwQVV9j2RZtmihfl7miDCSb5z5_MrzxLzyLBL_8xz446XrXIyigLuT

- title: 数字时代躺平文化的建构：基于青年亚文化视角 
  type: paper
  image: images/publications.jpg
  authors:
    - 路文廷
    - 张林
    - 牟怡
  publisher: 新闻记者
  date: '2023-06-20'
  link: https://chn.oversea.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2023&filename=XWJZ202306009&uniplatform=OVERSEA&v=ssm6Go5gBLK4NrhFUIgaiTHecfKMySlpJ2BKRljMMc2hJKpbXZrrqu_PBJbO2nXC
