- id: doi:10.1177/14614448231212822
  type: paper
  image: images/publications.jpg

- id: doi:10.1080/10447318.2023.2256554
  type: paper
  image: images/publications.jpg

- id: doi:10.1071/SH22025
  type: paper
  image: images/publications.jpg

- id: doi:10.1093/her/cyad012
  type: paper
  image: images/publications.jpg

- id: doi:10.1080/10447318.2022.2163350
  type: paper
  image: images/publications.jpg

- id: doi:10.1080/17543266.2022.2125589
  type: paper
  image: images/publications.jpg

- id: doi:10.15997/j.cnki.qnjz.2023.02.019
  type: paper
  image: images/publications.jpg

- id: doi:10.20050/j.cnki.xwdx.2023.05.010
  type: paper
  image: images/publications.jpg

- id: doi:10.16057/j.cnki.31-1171/g2.2023.06.004
  type: paper
  image: images/publications.jpg